language: scala
scala:
- 2.10.4
before_script: ./make_credentials.sh
script: sbt clean test

notifications:
  email:
    recipients:
    - krisztian.lachata@gmail.com
    
env:
  global:
    - secure: ""

# Publish to Sonatype if building master
after_success:
  - "[[ $TRAVIS_BRANCH == \"master\" ]] && [[ $TRAVIS_PULL_REQUEST == \"false\" ]] && sbt publish"
